In [17]:
import os
import base64
from sqlalchemy import create_engine
import pymysql
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sys
sys.path.append("/home/karan.verma")
from verification_guardrails import get_type_of_text

In [18]:
ipaddr = 'speak2recharge.mysql.database.azure.com'
db_name = 'speech_uat'
passwd = 'S2RPass7'
userid = 'myadmin@speak2recharge'
dest_sql = "mysql+mysqldb://" + userid + ":" + passwd + "@" + ipaddr + "/" + db_name + "?charset=utf8&use_unicode=0"
sql_engine = create_engine(dest_sql,pool_recycle=3600)
db_connection    = sql_engine.connect()

In [3]:
data_s2r = pd.read_sql('select * from data_hindi as A inner join data_validator_hindi as B on A.id = B.id  where A.tag in (51,52) and A.assigned=1 and A.verified=20;', db_connection)
data_s2r.describe()

,id,user_id,assigned,tag,flag_decode,hash,upload_time,uploaded,verified,synced,...,cost_per_phonem,fw_per_phonem,lw_per_phonem,skip_max_value,skip_min_value,skip_max_pos,skip_min_pos,lm_value,cer,wer
count,1.120254e+06,1.120254e+06,1120254.0,1.120254e+06,1120254.0,1120254.0,1120254.0,1120254.0,1120254.0,1.120254e+06,...,1.120254e+06,1.120254e+06,1.120254e+06,1.120254e+06,1.120254e+06,1.120254e+06,1.120254e+06,1120254.0,1120254.0,1120254.0
mean,2.473613e+07,2.167263e+05,1.0,5.161020e+01,0.0,9.0,0.0,1.0,20.0,9.923267e-01,...,3.745960e-01,3.132320e-01,3.121010e-01,9.518295e-01,3.900079e-01,5.072726e+00,5.960959e+00,0.0,1.0,1.0
std,4.769970e+05,1.652746e+04,0.0,4.877050e-01,0.0,0.0,0.0,0.0,0.0,8.726046e-02,...,2.934523e-01,2.819203e-01,2.967719e-01,6.887112e-01,5.308809e-01,7.846106e+00,8.088012e+00,0.0,0.0,0.0
min,2.393082e+07,2.649800e+04,1.0,5.100000e+01,0.0,9.0,0.0,1.0,20.0,0.000000e+00,...,1.004178e-03,1.476880e-04,2.925230e-04,1.109527e-03,-5.576468e-02,0.000000e+00,0.000000e+00,0.0,1.0,1.0
25%,2.432469e+07,2.173580e+05,1.0,5.100000e+01,0.0,9.0,0.0,1.0,20.0,1.000000e+00,...,1.412976e-01,7.814321e-02,6.040582e-02,3.892672e-01,2.447336e-02,0.000000e+00,0.000000e+00,0.0,1.0,1.0
50%,2.471471e+07,2.193040e+05,1.0,5.200000e+01,0.0,9.0,0.0,1.0,20.0,1.000000e+00,...,2.920832e-01,2.334265e-01,2.186428e-01,8.173976e-01,1.428103e-01,1.000000e+00,2.000000e+00,0.0,1.0,1.0
75%,2.515512e+07,2.226700e+05,1.0,5.200000e+01,0.0,9.0,0.0,1.0,20.0,1.000000e+00,...,5.318708e-01,4.796321e-01,4.919774e-01,1.399511e+00,5.654382e-01,8.000000e+00,9.000000e+00,0.0,1.0,1.0
max,2.557554e+07,2.283950e+05,1.0,5.200000e+01,0.0,9.0,0.0,1.0,20.0,1.000000e+00,...,9.999991e-01,1.199981e+00,1.199989e+00,3.499974e+00,3.499974e+00,1.010000e+02,9.200000e+01,0.0,1.0,1.0

In [5]:
data_s2r_new = data_s2r
data_s2r_new.columns

Index(['id', 'user_id', 'text', 'utf_text', 'base_dir', 'audio_file',
       'assigned', 'tag', 'flag_decode', 'hash', 'upload_date',
       'verified_time', 'upload_time', 'uploaded', 'verified', 'synced',
       'last_modifed', 'create_date', 'length', 'table_id', 'id', 'user_id',
       'lang', 'length', 'verified', 'synced', 'cost_value', 'cost_per_phonem',
       'fw_per_phonem', 'lw_per_phonem', 'skip_max_value', 'skip_min_value',
       'skip_max_pos', 'skip_min_pos', 'lm_value', 'cer', 'wer', 'decoded_utf',
       'gender', 'decoded', 'last_modifed'],
      dtype='object')

In [14]:
data_s2r_new['utf_text_decoded'] = data_s2r_new['utf_text'].apply(base64.urlsafe_b64decode).str.decode('utf8', errors='ignore').dropna()
data_s2r_new['type_of_text'] = data_s2r_new['utf_text_decoded'].apply(get_type_of_text)
data_s2r_new['word_len'] = data_s2r_new['utf_text_decoded'].str.split().apply(len)
pd.set_option('display.max_columns',100)
data_s2r_new.head()

,id,user_id,text,utf_text,base_dir,audio_file,assigned,tag,flag_decode,hash,upload_date,verified_time,upload_time,uploaded,verified,synced,last_modifed,create_date,length,table_id,id,user_id,lang,length,verified,synced,cost_value,cost_per_phonem,fw_per_phonem,lw_per_phonem,skip_max_value,skip_min_value,skip_max_pos,skip_min_pos,lm_value,cer,wer,decoded_utf,gender,decoded,last_modifed,utf_text_decoded,type_of_text,word_len
0,23930817,215555,b'0',b'4KSu4KS54KWH4KSm4KWACg==',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930817.opus',1,51,0,9,2020-02-20 18:53:09,None,0,1,20,1,None,2020-02-18 16:34:07,0,14138989,23930817,215555,0,113,1,1,0.256964,0.990000,1.082698,1.091845,2.719941,2.719941,0.0,0.0,0.0,1.0,1.0,b' ',b'NA',b' ',2020-02-20 13:23:17,à¤®à¤¹à¥‡à¤¦à¥€\n,0,1
1,23930819,215555,b'0',b'4KS44KS-4KSh4KWA4KSv4KS-Cg==',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930819.opus',1,51,0,9,2020-02-20 18:53:04,None,0,1,20,1,None,2020-02-18 16:34:07,0,14138987,23930819,215555,0,131,1,1,0.126224,0.990000,0.544816,0.572194,1.386825,1.386825,0.0,0.0,0.0,1.0,1.0,b' ',b'NA',b' ',2020-02-20 13:23:17,à¤¸à¤¾à¤¡à¥€à¤¯à¤¾\n,0,1
2,23930820,215555,b'0',b'4KSu4KS54KS_4KSy4KS-IOCknOClguCkpOClhwo=',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930820.opus',1,51,0,9,2020-02-20 18:53:02,None,0,1,20,1,None,2020-02-18 16:34:07,0,14138986,23930820,215555,0,161,1,1,0.004834,0.017035,0.012441,0.017923,0.029005,0.029005,0.0,0.0,0.0,1.0,1.0,b' ',b'NA',b' ',2020-02-20 13:23:17,à¤®à¤¹à¤¿à¤²à¤¾ à¤œà¥‚à¤¤à¥‡\n,0,2
3,23930821,215555,b'0',b'4KSw4KWL4KSXCg==',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930821.opus',1,51,0,9,2020-02-20 18:52:59,None,0,1,20,1,None,2020-02-18 16:34:07,0,14138985,23930821,215555,0,131,1,1,0.039597,0.990000,0.147564,0.327222,0.451539,0.451539,0.0,0.0,0.0,1.0,1.0,b' ',b'NA',b' ',2020-02-20 13:23:17,à¤°à¥‹à¤—\n,0,1
4,23930822,215555,b'0',b'4KSV4KSC4KSq4KSo4KWAIOCkleCkviDgpJzgpYLgpKTg...,b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930822.opus',1,51,0,9,2020-02-20 18:52:50,None,0,1,20,1,None,2020-02-18 16:34:07,0,14138984,23930822,215555,0,167,1,1,0.054699,0.155993,0.011107,0.217053,0.156488,0.037839,2.0,0.0,0.0,1.0,1.0,b' ',b'NA',b' ',2020-02-20 13:22:57,à¤•à¤‚à¤ªà¤¨à¥€ à¤•à¤¾ à¤œà¥‚à¤¤à¤¾\n,0,3

# Total Data

In [11]:
data_s2r_new_usable_hr = data_s2r_new["length"].sum()/(60*1000*60)
print("Total Audio Duration in hours  :- ", data_s2r_new_usable_hr)

data_s2r_new_count = data_s2r_new["length"].count()
print("Total files                    :- ", data_s2r_new_count)

data_s2r_new_mean = data_s2r_new["length"].mean()
print("Mean Audio Duration            :- ", data_s2r_new_mean)

Total Audio Duration in hours  :-  length     0.000000
length    87.587748
dtype: float64
Total files                    :-  length    1120254
length    1120254
dtype: int64
Mean Audio Duration            :-  length      0.000000
length    281.468213
dtype: float64

## My exp

In [19]:
data_s2r_1 = pd.read_sql('select * from data_hindi where tag in (51,52) and verified=20;', db_connection)
data_s2r_1.describe()

,id,user_id,assigned,tag,flag_decode,hash,upload_time,uploaded,verified,synced,length
count,1.120254e+06,1.120254e+06,1120254.0,1.120254e+06,1120254.0,1120254.0,1120254.0,1120254.0,1120254.0,1.120254e+06,1120254.0
mean,2.473613e+07,2.167263e+05,1.0,5.161020e+01,0.0,9.0,0.0,1.0,20.0,9.923267e-01,0.0
std,4.769970e+05,1.652746e+04,0.0,4.877050e-01,0.0,0.0,0.0,0.0,0.0,8.726046e-02,0.0
min,2.393082e+07,2.649800e+04,1.0,5.100000e+01,0.0,9.0,0.0,1.0,20.0,0.000000e+00,0.0
25%,2.432469e+07,2.173580e+05,1.0,5.100000e+01,0.0,9.0,0.0,1.0,20.0,1.000000e+00,0.0
50%,2.471471e+07,2.193040e+05,1.0,5.200000e+01,0.0,9.0,0.0,1.0,20.0,1.000000e+00,0.0
75%,2.515512e+07,2.226700e+05,1.0,5.200000e+01,0.0,9.0,0.0,1.0,20.0,1.000000e+00,0.0
max,2.557554e+07,2.283950e+05,1.0,5.200000e+01,0.0,9.0,0.0,1.0,20.0,1.000000e+00,0.0

In [20]:
data_s2r_1.head()

,id,user_id,text,utf_text,base_dir,audio_file,assigned,tag,flag_decode,hash,upload_date,verified_time,upload_time,uploaded,verified,synced,last_modifed,create_date,length
0,23930817,215555,b'0',b'4KSu4KS54KWH4KSm4KWACg==',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930817.opus',1,51,0,9,2020-02-20 18:53:09,None,0,1,20,1,None,2020-02-18 16:34:07,0
1,23930819,215555,b'0',b'4KS44KS-4KSh4KWA4KSv4KS-Cg==',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930819.opus',1,51,0,9,2020-02-20 18:53:04,None,0,1,20,1,None,2020-02-18 16:34:07,0
2,23930820,215555,b'0',b'4KSu4KS54KS_4KSy4KS-IOCknOClguCkpOClhwo=',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930820.opus',1,51,0,9,2020-02-20 18:53:02,None,0,1,20,1,None,2020-02-18 16:34:07,0
3,23930821,215555,b'0',b'4KSw4KWL4KSXCg==',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930821.opus',1,51,0,9,2020-02-20 18:52:59,None,0,1,20,1,None,2020-02-18 16:34:07,0
4,23930822,215555,b'0',b'4KSV4KSC4KSq4KSo4KWAIOCkleCkviDgpJzgpYLgpKTg...,b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930822.opus',1,51,0,9,2020-02-20 18:52:50,None,0,1,20,1,None,2020-02-18 16:34:07,0

In [23]:
ipaddr = 'speak2recharge.mysql.database.azure.com'
db_name = 'speech_process'
passwd = 'S2RPass7'
userid = 'myadmin@speak2recharge'
dest_sql = "mysql+mysqldb://" + userid + ":" + passwd + "@" + ipaddr + "/" + db_name + "?charset=utf8&use_unicode=0"
sql_engine = create_engine(dest_sql,pool_recycle=3600)
db_connection_1    = sql_engine.connect()

In [24]:
data_s2r_prev = pd.read_sql('select * from speech_process.s2r_hindi_vs_3_lifestyle_1_27082020;', db_connection_1)
data_s2r_prev.describe()

,id,user_id,assigned,tag,flag_decode,hash,upload_time,uploaded,verified,synced,length
count,1.000000e+06,1000000.000000,1000000.0,1000000.000000,1000000.0,1000000.0,1000000.0,1000000.0,1000000.0,1000000.000000,1000000.000000
mean,2.478771e+07,216765.966963,1.0,51.750000,0.0,9.0,0.0,1.0,20.0,0.990739,288.362064
std,3.979907e+05,17272.841311,0.0,0.433013,0.0,0.0,0.0,0.0,0.0,0.095787,168.817564
min,2.393082e+07,26498.000000,1.0,51.000000,0.0,9.0,0.0,1.0,20.0,0.000000,41.000000
25%,2.454689e+07,218031.000000,1.0,51.750000,0.0,9.0,0.0,1.0,20.0,1.000000,179.000000
50%,2.481236e+07,220017.000000,1.0,52.000000,0.0,9.0,0.0,1.0,20.0,1.000000,251.000000
75%,2.512431e+07,222559.000000,1.0,52.000000,0.0,9.0,0.0,1.0,20.0,1.000000,353.000000
max,2.541698e+07,224725.000000,1.0,52.000000,0.0,9.0,0.0,1.0,20.0,1.000000,1721.000000

In [25]:
data_s2r_prev.head()

,id,user_id,text,utf_text,base_dir,audio_file,assigned,tag,flag_decode,hash,upload_date,verified_time,upload_time,uploaded,verified,synced,last_modifed,create_date,length
0,24416807,218739,b'0',b'4KSu4KWI4KSfIOCkueCkteCkvuCkqOCkviDgpJrgpL7g...,b'/home/software/data/uploads_v2/hindi/2020-04...,b'218739_1_24416807.opus',1,51,0,9,2020-04-06 12:40:19,None,0,1,20,1,None,2020-03-22 20:44:12,185
1,24214084,169845,b'0',b'4KS44KWJ4KSVIOCkruCkv-CksuClh-Ckl-ClgCDgpJXg...,b'/home/software/data/uploads_v2/hindi/2020-03...,b'169845_1_24214084.opus',1,51,0,9,2020-03-26 11:06:57,None,0,1,20,1,None,2020-03-22 20:44:12,239
2,24469355,218978,b'0',b'4KSu4KWL4KSc4KS-IOCkruClh-CkqCDgpJXgpL4g4KSh...,b'/home/software/data/uploads_v2/hindi/2020-04...,b'218978_1_24469355.opus',1,51,0,9,2020-04-08 17:14:50,None,0,1,20,1,None,2020-03-22 20:44:12,203
3,24517361,218734,b'0',b'4KSV4KWN4KSv4KS-IOCkuOCkrCDgpLngpYgg4KSs4KWN...,b'/home/software/data/uploads_v2/hindi/2020-04...,b'218734_1_24517361.opus',1,51,0,9,2020-04-10 22:22:54,None,0,1,20,1,None,2020-03-22 20:44:12,707
4,24482697,218843,b'0',b'4KSu4KWB4KSd4KWHIOCkpuCkv-CkteCkuOCljeCksOCl...,b'/home/software/data/uploads_v2/hindi/2020-04...,b'218843_1_24482697.opus',1,51,0,9,2020-04-09 08:31:18,None,0,1,20,1,None,2020-03-22 20:44:12,455

In [26]:
data_s2r_1.head()

,id,user_id,text,utf_text,base_dir,audio_file,assigned,tag,flag_decode,hash,upload_date,verified_time,upload_time,uploaded,verified,synced,last_modifed,create_date,length
0,23930817,215555,b'0',b'4KSu4KS54KWH4KSm4KWACg==',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930817.opus',1,51,0,9,2020-02-20 18:53:09,None,0,1,20,1,None,2020-02-18 16:34:07,0
1,23930819,215555,b'0',b'4KS44KS-4KSh4KWA4KSv4KS-Cg==',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930819.opus',1,51,0,9,2020-02-20 18:53:04,None,0,1,20,1,None,2020-02-18 16:34:07,0
2,23930820,215555,b'0',b'4KSu4KS54KS_4KSy4KS-IOCknOClguCkpOClhwo=',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930820.opus',1,51,0,9,2020-02-20 18:53:02,None,0,1,20,1,None,2020-02-18 16:34:07,0
3,23930821,215555,b'0',b'4KSw4KWL4KSXCg==',b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930821.opus',1,51,0,9,2020-02-20 18:52:59,None,0,1,20,1,None,2020-02-18 16:34:07,0
4,23930822,215555,b'0',b'4KSV4KSC4KSq4KSo4KWAIOCkleCkviDgpJzgpYLgpKTg...,b'/home/software/data/uploads_v2/hindi/2020-02...,b'215555_1_23930822.opus',1,51,0,9,2020-02-20 18:52:50,None,0,1,20,1,None,2020-02-18 16:34:07,0

In [31]:
tids_new = set(data_s2r_1.id.to_list())
tids_prev = set(data_s2r_prev.id.to_list())
intersect = list(tids_new.intersection(tids_prev))
intersect[:10]

[25165824,
 25165825,
 25165826,
 25165827,
 25165828,
 25165829,
 25165830,
 25165831,
 25165832,
 25165833]